apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ex2-dev
data:
  # Backend configuration
  PORT: "5000"              # Backend listens on this port
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "app-deploy-k8s-db"
  LOG_LEVEL: "info"